### ISSUE TITLE
settings api is broken

### ISSUE THREAD

**Issue by no-boot-device** [Cynosphere/EndPwnPlugins#7]
```
[EPAPI] settingsapi.js failed to initialize properly:

 TypeError: Cannot read property 'sections' of undefined
    at Object.start (eval at evaluate (/home/bootsy/.config/discord/epapi.js:22:15), <anonymous>:26:43)
    at fs.readdirSync.forEach.x (/home/bootsy/.config/discord/epapi.js:328:52)
    at Array.forEach (native)
    at init (/home/bootsy/.config/discord/epapi.js:322:71)
    at i (https://discordapp.com/assets/16b5a242a8c1b23652da.js:104:30575)
```

**Comment by Cynosphere** [comment]
Issue with latest update not having webpack replacements run for plugins for some odd reason. Plugin itself is fine, just CRISPR needing some help or something.

**Comment by no-boot-device** [comment]
then why does fixmentions.js work fine?
